"""Policy engine data models.

DEPRECATED: This module has been reorganized into vpo.policy.types.
This shim provides backward compatibility. Update imports to use:

    from vpo.policy.types import PolicySchema, Plan, TrackType, ...

All types, enums, and constants have been moved to vpo.policy.types.
"""

import warnings

# Re-export everything from types.py for backward compatibility
from vpo.policy.types import (
    # Constants
    CANONICAL_OPERATION_ORDER,
    DEFAULT_CRF_VALUES,
    DEFAULT_TRACK_ORDER,
    MP4_INCOMPATIBLE_CODECS,
    RESOLUTION_MAP,
    VALID_AUDIO_CODECS,
    VALID_PRESETS,
    VALID_RESOLUTIONS,
    VALID_VIDEO_CODECS,
    X264_X265_TUNES,
    # Enums
    ActionType,
    # Condition types
    AndCondition,
    # Configuration classes
    AttachmentFilterConfig,
    AudioActionsConfig,
    AudioFilterConfig,
    AudioIsMultiLanguageCondition,
    AudioPreservationRule,
    AudioSynthesisConfig,
    # Plan and result types
    AudioTrackAction,
    AudioTranscodeConfig,
    Comparison,
    ComparisonOperator,
    # Type aliases
    Condition,
    ConditionalAction,
    ConditionalResult,
    # Action types
    ConditionalRule,
    ContainerChange,
    ContainerConfig,
    CountCondition,
    DefaultFlagsConfig,
    ExistsCondition,
    FailAction,
    FileProcessingResult,
    GlobalConfig,
    HardwareAccelConfig,
    HardwareAccelMode,
    IsDubbedCondition,
    IsOriginalCondition,
    LanguageFallbackConfig,
    NotCondition,
    OnErrorMode,
    OperationType,
    OrCondition,
    PhaseDefinition,
    PhasedPolicySchema,
    PhaseExecutionContext,
    PhaseExecutionError,
    PhaseOutcome,
    PhaseResult,
    PhaseSkipCondition,
    Plan,
    PlannedAction,
    PluginMetadataCondition,
    PluginMetadataOperator,
    PluginMetadataReference,
    PolicySchema,
    ProcessingPhase,
    QualityMode,
    QualitySettings,
    RuleEvaluation,
    RunIfCondition,
    ScaleAlgorithm,
    ScalingSettings,
    SetDefaultAction,
    SetForcedAction,
    SetLanguageAction,
    SkipAction,
    SkipCondition,
    SkipFlags,
    SkipIfExistsCriteria,
    SkipReason,
    SkipReasonType,
    SkipType,
    SubtitleActionsConfig,
    SubtitleFilterConfig,
    SynthesisTrackDefinitionRef,
    TitleMatch,
    TrackDisposition,
    TrackFilters,
    TrackFlagChange,
    TrackLanguageChange,
    TrackType,
    TranscodePolicyConfig,
    TranscriptionPolicyOptions,
    # Backward compatibility alias
    V11PolicySchema,
    VideoTranscodeAction,
    VideoTranscodeConfig,
    VideoTranscodeResult,
    WarnAction,
    WorkflowConfig,
    # Functions
    get_default_crf,
    parse_bitrate,
)

# Issue deprecation warning on import
warnings.warn(
    "vpo.policy.models is deprecated. Use vpo.policy.types instead.",
    DeprecationWarning,
    stacklevel=2,
)

__all__ = [
    # Enums
    "ActionType",
    "ComparisonOperator",
    "HardwareAccelMode",
    "OnErrorMode",
    "OperationType",
    "PhaseOutcome",
    "PluginMetadataOperator",
    "ProcessingPhase",
    "QualityMode",
    "ScaleAlgorithm",
    "SkipReasonType",
    "SkipType",
    "TrackType",
    # Configuration classes
    "AttachmentFilterConfig",
    "AudioActionsConfig",
    "AudioFilterConfig",
    "AudioPreservationRule",
    "AudioSynthesisConfig",
    "AudioTranscodeConfig",
    "ContainerConfig",
    "DefaultFlagsConfig",
    "GlobalConfig",
    "HardwareAccelConfig",
    "LanguageFallbackConfig",
    "PhaseDefinition",
    "PhasedPolicySchema",
    "PolicySchema",
    "QualitySettings",
    "ScalingSettings",
    "SkipCondition",
    "SkipIfExistsCriteria",
    "SubtitleActionsConfig",
    "SubtitleFilterConfig",
    "SynthesisTrackDefinitionRef",
    "TranscodePolicyConfig",
    "TranscriptionPolicyOptions",
    "VideoTranscodeConfig",
    "WorkflowConfig",
    # Condition types
    "AndCondition",
    "AudioIsMultiLanguageCondition",
    "Comparison",
    "CountCondition",
    "ExistsCondition",
    "IsDubbedCondition",
    "IsOriginalCondition",
    "NotCondition",
    "OrCondition",
    "PluginMetadataCondition",
    "TitleMatch",
    "TrackFilters",
    # Action types
    "ConditionalRule",
    "FailAction",
    "PluginMetadataReference",
    "SetDefaultAction",
    "SetForcedAction",
    "SetLanguageAction",
    "SkipAction",
    "WarnAction",
    # Plan and result types
    "AudioTrackAction",
    "ConditionalResult",
    "ContainerChange",
    "FileProcessingResult",
    "PhaseExecutionContext",
    "PhaseExecutionError",
    "PhaseResult",
    "PhaseSkipCondition",
    "Plan",
    "PlannedAction",
    "RuleEvaluation",
    "RunIfCondition",
    "SkipFlags",
    "SkipReason",
    "TrackDisposition",
    "TrackFlagChange",
    "TrackLanguageChange",
    "VideoTranscodeAction",
    "VideoTranscodeResult",
    # Type aliases
    "Condition",
    "ConditionalAction",
    # Constants
    "CANONICAL_OPERATION_ORDER",
    "DEFAULT_CRF_VALUES",
    "DEFAULT_TRACK_ORDER",
    "MP4_INCOMPATIBLE_CODECS",
    "RESOLUTION_MAP",
    "VALID_AUDIO_CODECS",
    "VALID_PRESETS",
    "VALID_RESOLUTIONS",
    "VALID_VIDEO_CODECS",
    "X264_X265_TUNES",
    # Functions
    "get_default_crf",
    "parse_bitrate",
    # Backward compatibility alias
    "V11PolicySchema",
]
